[package]
name = "kchfgt"
version = "0.1.0"
authors = ["katk3n"]
description = "Creative coding tool with shaders and sounds"
edition = "2021"
license = "MIT"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }
clap = { version = "4.5.26", features = ["derive"] }
